### ISSUE TITLE
JWT 토큰 관련 설명

### ISSUE THREAD

**Issue by stepano9002** [n0ch4t/eerycode#1]
엑세스 토큰 만든거 같은거 아무것도 없으면 
1. - 우선 yarn add jsonmwebtoken 설치하고
2. - .env 파일 만들고 이거도 yarn add dotenv 해서 설치하고
3. - 비밀키 아무거나 원하는거 입력해주고
4. - .env파일안에 PORT =4000 , DB_URL= 님꺼쓰고  , JWT_SECRET= 여기 비밀키 입력 (""없이)

토큰 만드는 인스턴스 메서드 만들어주기 

몽고디비라치면 
`UserSchema.methods.generateToken = function (){
const token = jwt.sing(  //jwt는 yarn으로 다운받은거 쓰는거 임포트한거임
{
//토큰안에 집어 넣고 싶은값 
_id: id,
...
},
process.env.JWT_SECRET,
{
expiresIn : '7d', //7일 유통기한
}
);
return token;`

이렇게 하고 검증
`
const jwtMiddleware = (ctx, next)=>{
const token = ctx.cookies.get('access_token');
if(!token) return next();
try{
const decoded = jwt.verify(token, process.env.JWT_SECRET);
retrun next();
}
catch(e){
return next();
}
};
`
그리고 이 미들웨어 app.use(jwtMiddleware) 이거 쓸때 위쪽 상단에 써야함 

이방법 아니면 그냥 
`
엑세스 토큰 뭐 따로 있다면 그냥 나중에 검증할때 이렇게만써도댐 
  추후에 이메일 정보를 가지고 구글메일API를 쓴다면 렌더링 해줘야한다면 써야 할 베어리어 인증
      .get(Gmail_URI, {
        headers: { Authorization: `Bearer ${response.accessToken} },
      })

`

**Comment by n0ch4t** [comment]
뭐야 그거 여기꺼 아님
